# Generated by Django 5.2.7 on 2026-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0002_customuser_is_approved_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hifdh',
            field=models.CharField(choices=[('none', 'Not Memorizing'), ('juz_1_5', 'Juz 1-5'), ('juz_6_10', 'Juz 6-10'), ('juz_11_15', 'Juz 11-15 (Half Quran)'), ('juz_16_20', 'Juz 16-20'), ('juz_21_25', 'Juz 21-25'), ('juz_26_30', 'Juz 26-30 (Full Quran)')], default='none', help_text="Select the student's Quran memorization level", max_length=50, verbose_name='Quran Memorization (Hifdh) Level'),
        ),
    ]
