# Generated by Django 5.2.7 on 2026-07-01 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0003_customuser_middle_name_studentprofile_hifdh'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cups',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cups'),
        ),
    ]
